17 fix front running attack in allocationidtracker
semiotic-ai/timeline-aggregation-protocol-contracts pull request #19
Opened 2023-06-28 20:04 UTC by ColePBryan

2023-06-28 20:20 UTC, tmigone approved these changes

2023-06-28 23:30 UTC, aasseman requested changes

2023-06-28 23:30 UTC, aasseman commented on src/AllocationIDTracker.sol
> +     * @param proof ECDSA Proos signed by receiver consisting of packed (sender address, allocationID, collateral contract address).
```suggestion
     * @param proof ECDSA Proof signed by the receiver consisting of packed (sender address, allocationID, collateral contract address).
```

2023-06-30 16:57 UTC, aasseman approved these changes

2023-06-30 19:05 UTC, merged

2025-08-25 01:37 UTC, Roseymr approved these changes