feat: updates revert with string to revert with custom errors
semiotic-ai/timeline-aggregation-protocol-contracts pull request #24
Opened 2023-07-13 18:11 UTC by ColePBryan

2023-07-13 18:45 UTC, aasseman requested changes

2023-07-13 18:45 UTC, aasseman commented on src/Collateral.sol
>              : account.amountThawing;
This should be removed now

2023-07-13 20:09 UTC, aasseman approved these changes
LGTM

2023-07-14 13:32 UTC, tmigone requested changes

2023-07-14 13:32 UTC, tmigone commented on src/AllocationIDTracker.sol
>          return true;
The return could be removed from this function since we are not using it anywhere and it's a private func.

2023-07-14 13:32 UTC, tmigone commented on src/AllocationIDTracker.sol
> +    error AllocationIDPreviouslyClaimed();
Can we add the alloId to the error?

2023-07-14 13:32 UTC, tmigone commented on src/Collateral.sol
> +    error SignerNotAuthorizedBySender();
Here we could add signer and sender

2023-07-14 13:32 UTC, tmigone commented on src/Collateral.sol
>          return true;
Same, we could remove the return value here.

2023-07-14 13:32 UTC, tmigone commented on src/Collateral.sol
> +        account.balance -= amount; // Reduce the balance by the withdrawn amount (no underflow risk)
Why was the unchecked removed here? Not that it makes that big of a difference but could save some gas given the previous check above.

2023-07-19 19:12 UTC, merged