feat(collateral-contract): allows max withdrawal for insufficient col…
semiotic-ai/timeline-aggregation-protocol-contracts pull request #25
Opened 2023-07-18 17:21 UTC by ColePBryan

…lateral available

allows calling redeem when the available collateral is less than the amount owed on provided RAV. The receiver will receive all of the available collateral and the allocation will be marked as redeemed.

2023-07-18 18:47 UTC, aasseman requested changes
LGTM otherwise

2023-07-18 18:47 UTC, aasseman commented on test/Collateral.t.sol
> +            remainingCollateral,
Why not 
```suggestion
            uint128(0),
```
?

2023-07-19 14:36 UTC, tmigone approved these changes
Looks good to me. The only suggestion I have is to make `collateralAccounts` a public variable. Since allos are marked as used, it's nice if we can facilitate indexers knowing what the collateral balance is before submitting the transaction so they know what to expect. Making it a public variable means it gets a getter which makes checking this easier.


Also `authorizedSigners` could also be public unless we have a reason not to.

2023-07-19 19:27 UTC, ColePBryan commented
> Looks good to me. The only suggestion I have is to make `collateralAccounts` a public variable. Since allos are marked as used, it's nice if we can facilitate indexers knowing what the collateral balance is before submitting the transaction so they know what to expect. Making it a public variable means it gets a getter which makes checking this easier.
> 
> Also `authorizedSigners` could also be public unless we have a reason not to.

We do have 3 separate functions to get info from collateral accounts ( `getCollateralAccount`, `getCollateralAccountFromSignerAddress`, `getCollateralAmount`). We could just remove the `getCollateralAccount` and make it public. There isn't a reason that authorizedSigners is not public, I can change that as well.

2023-07-19 20:59 UTC, aasseman approved these changes

2023-07-20 14:25 UTC, tmigone approved these changes

2023-07-20 15:25 UTC, merged